version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgre.3110
      POSTGRES_DB: telusko
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data  # <-- Persist database data

  app:
#    build: .
    image: pratishthabp/spring-web-app:v1.0
    container_name: spring-app
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/telusko
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Postgre.3110
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres-data:
